name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch the latest commit, only
        fetch-depth: 1

    - name: Pull Docker base image
      run:  docker pull ubuntu:21.04

    - name: Build development Docker image
      run:  make dckr-image

    - name: Build application and tests executables
      run:  make dckr-build

    - name: Run tests
      run:  make dckr-test
